# Generated by Django 5.0.6 on 2024-06-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
    ]
